firstName = input("FirstName:")
middleName = input("MiddleName:")
lastName = input("lastName:")
print("Your Name:", firstName, middleName, lastName)
print('Your Initials Are:' + firstName[0], middleName[0], lastName[0], sep=".")
